import Navbar from "@/components/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Fredoka } from "next/font/google";

const fredoka = Fredoka({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Tutor Website",
  description: "Generated by me",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={fredoka.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
